spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cart_service
    username: root
    password: jiwon1923
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
  toss:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}
    callback-url: "/api/payments/callback"

  kafka:
    text-bootstrap-servers: localhost:9092
logging:
  level:
    org:
      springframework:
        web: DEBUG
        cloud: DEBUG

product-service:
  url: http://localhost:8080